/** Declaration file generated by dts-gen */

export = javascript_time_ago;

declare class javascript_time_ago {
    constructor(...args: any[]);

    format(input: any, ...args: any[]): any;

    get_locale_data(...args: any[]): any;

    static default: any;

    static default_locale: string;

    static intlDateTimeFormatSupported(): any;

    static intlDateTimeFormatSupportedLocale(locales: any): any;

    static locale(locale_data: any): void;

    static locales: {
    };

    static setDefaultLocale(locale: any): void;

}


